version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: expense_tracker_development
      POSTGRES_USER: expense_tracker
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
